FROM php:8.1-cli-alpine

ENV IPE_GD_WITHOUTAVIF=1
COPY --from=composer /usr/bin/composer /usr/bin/composer
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/bin/

RUN apk add --no-cache git zip unzip && \
    install-php-extensions bcmath gd intl sockets bz2 gmp soap zip gmp
